events {}

http {
    client_body_temp_path temp/client_body_temp;
    proxy_temp_path       temp/proxy_temp;
    fastcgi_temp_path     temp/fastcgi_temp;
    uwsgi_temp_path       temp/uwsgi_temp;
    scgi_temp_path        temp/scgi_temp;

    server {
        listen 80;

        location / {
            proxy_pass http://frontend:3000;
        }

        location /api/ {
            proxy_pass http://backend:5000/;
        }
    }
}