name: Deploy demo-app application to Windows Server
run-name: ${{ github.actor }} triggered demo-app deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # 🔐 Login to Docker Hub
    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 🏗️ Build & Push Backend
    - name: Build and Push Backend to Docker Hub
      shell: powershell
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

    # 🏗️ Build & Push Frontend
    - name: Build and Push Frontend to Docker Hub
      shell: powershell
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    # 🏗️ Build & Push Nginx
    - name: Build and Push Nginx to Docker Hub
      shell: powershell
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx:latest ./nginx
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Fetches the latest repository code for the workflow
      - name: Checkout code
        uses: actions/checkout@v4

        # Transfers docker-compose and nginx config files to the EC2 instance
      - name: Copy configs to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          source: "docker-compose.yml,nginx/nginx.conf"
          target: "C:/project"

        # Connects via SSH and recreates containers using Docker Compose
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          script: |
            cmd /c "cd C:\project && docker compose -f C:\project\docker-compose.yml down --remove-orphans && docker network prune -f && docker compose -f C:\project\docker-compose.yml up -d"

        # Verifies deployment by calling backend health endpoint
      - name: Health Check
        run: |
          curl -f http://${{ secrets.EC2_HOST }}/api/health